{
 "title": "APIServer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "verb",
    "query": {
     "query": "label_values(apiserver_request_total, verb)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(apiserver_request_total, resource)"
    }
   },
   {
    "name": "client",
    "query": {
     "query": "label_values(apiserver_request_total, client)"
    }
   },
   { "name": "quantile", "query": "0.99,0.9,0.5" },
   { "name": "interval", "query": "1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "API QPS",
   "type": "stat",
   "description": "当前集群的每秒请求数总量（包括全部读写请求）",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{job=\"apiserver\"}[$interval]))"
    }
   ]
  },
  {
   "title": "读请求成功率",
   "type": "stat",
   "description": "每秒的读请求成功率",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{job=\"apiserver\",code=~\"20.*\",verb=~\"GET|LIST\"}[$interval]))/sum(irate(apiserver_request_total{job=\"apiserver\",verb=~\"GET|LIST\"}[$interval]))"
    }
   ]
  },
  {
   "title": "写请求成功率",
   "type": "stat",
   "description": "每秒的修改请求的成功率",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{job=\"apiserver\",code=~\"20.*\",verb!~\"GET|LIST|WATCH|CONNECT\"}[$interval]))/sum(irate(apiserver_request_total{job=\"apiserver\",verb!~\"GET|LIST|WATCH|CONNECT\"}[$interval]))"
    }
   ]
  },
  {
   "title": "在处理读请求数量",
   "type": "stat",
   "description": "集群内在处理的读请求总量",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{job=\"apiserver\",requestKind=\"readOnly\"})"
    },
    {
     "expr": "sum(apiserver_current_inflight_requests{job=\"apiserver\",request_kind=\"readOnly\"})"
    }
   ]
  },
  {
   "title": "在处理写请求数量",
   "type": "stat",
   "description": "集群内在处理的写请求总量",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(apiserver_current_inflight_requests{job=\"apiserver\",requestKind=\"mutating\"})"
    },
    {
     "expr": " sum(apiserver_current_inflight_requests{job=\"apiserver\",request_kind=\"mutating\"})"
    }
   ]
  },
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GET读请求时延 P[$quantile]",
   "type": "timeseries",
   "description": "GET读请求时延。",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",verb=\"GET\",resource!=\"\",subresource!~\"log|proxy\"}[$interval])) by (pod, verb, resource, subresource, scope, le))",
     "legendFormat": "{{pod}} - {{verb}} - {{resource}}  - {{subresource}} - {{scope}}"
    }
   ]
  },
  {
   "title": "LIST读请求时延 P[$quantile]",
   "type": "timeseries",
   "description": "LIST读请求时延。",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",verb=\"LIST\"}[$interval])) by (pod, verb, resource, scope, le)) ",
     "legendFormat": "{{pod}} - {{verb}} - {{resource}}  - {{scope}}"
    }
   ]
  },
  {
   "title": "写请求时延 P[$quantile]",
   "type": "timeseries",
   "description": "写请求时延。",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",verb!~\"GET|WATCH|LIST|CONNECT\"}[$interval])) by (pod, verb, resource, scope, le))",
     "legendFormat": "{{pod}} - {{verb}} - {{resource}}  - {{scope}}"
    }
   ]
  },
  {
   "title": "在处理读请求数量",
   "type": "timeseries",
   "description": "Apiserver当前在处理的读请求数量。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests{request_kind=\"readOnly\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "在处理写请求数量",
   "type": "timeseries",
   "description": "Apiserver当前在处理的写请求数量。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests{request_kind=\"mutating\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "资源分析",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "description": "内存使用量，单位字节。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_utilization_byte{job=\"apiserver\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU使用量",
   "type": "timeseries",
   "description": "CPU使用量，单位毫核。\n1核=1000毫核。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpu_utilization_core{container=\"kube-apiserver\"}*1000",
     "legendFormat": " {{instance}} "
    }
   ]
  },
  {
   "title": "QPS和时延",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "按 Verb 维度分析QPS [$verb] P[$quantile] ",
   "type": "timeseries",
   "description": "按 Verb 维度分析QPS。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb=~\"$verb\"}[$interval]))by(verb)",
     "legendFormat": " {{verb}} "
    }
   ]
  },
  {
   "title": "按 Verb + Resource 维度分析QPS  [$resource] P[$quantile]",
   "type": "timeseries",
   "description": "按 Verb + Resource 维度分析QPS。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb=~\"$verb\",resource=~\"$resource\"}[$interval]))by(verb,resource)",
     "legendFormat": "{{verb}} - {{resource}}"
    },
    {}
   ]
  },
  {
   "title": "按 Verb 维度分析请求时延 [$verb] P[$quantile] ",
   "type": "timeseries",
   "description": "按 Verb 维度分析请求时延。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{verb=~\"$verb\", verb!~\"WATCH|CONNECT\",resource!=\"\"}[$interval])) by (le,verb))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "按 Verb + Resource 维度分析请求时延 [$resource] P[$quantile] ",
   "type": "timeseries",
   "description": "按 Verb + Resource 维度分析请求时延。",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(apiserver_request_duration_seconds_bucket{verb=~\"$verb\", verb!~\"WATCH|CONNECT\", resource=~\"$resource\",resource!=\"\"}[$interval])) by (le,verb,resource))",
     "legendFormat": "{{verb}} - {{resource}}"
    }
   ]
  },
  {
   "title": "非 2xx 返回值的读请求 QPS [$interval]",
   "type": "timeseries",
   "description": "非 2xx 返回值的读请求 QPS。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb=~\"GET|LIST\",resource=~\"$resource\",code!~\"2.*\"}[$interval])) by (verb,resource,code)",
     "legendFormat": "{{verb}}/{{resource}} {{code}} "
    }
   ]
  },
  {
   "title": "非 2xx 返回值的写请求 QPS  [$interval]",
   "type": "timeseries",
   "description": "非 2xx 返回值的写请求 QPS。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{verb!~\"GET|LIST|WATCH\",verb=~\"$verb\",resource=~\"$resource\",code!~\"2.*\"}[$interval])) by (verb,resource,code)",
     "legendFormat": "{{verb}}/{{resource}} {{code}} "
    }
   ]
  },
  {
   "title": "Apiserver对Etcd请求时延 [$interval]",
   "type": "timeseries",
   "description": "Apiserver对Etcd请求时延分析。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(irate(etcd_request_duration_seconds_bucket[$interval])) by (le,operation,type,instance))\n",
     "legendFormat": "{{instance}} - {{operation}} - {{type}} "
    }
   ]
  },
  {
   "title": "准入控制器和 Webhook",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "准入控制器时延 [admit]",
   "type": "graph",
   "description": "展示使用到的admit类型准入控制器、操作、是否拒绝以及相应的执行时间。\n\n这是内建的准入控制器指标。每个准入控制器都有唯一的名字，可以通过操作、API资源和操作类型维度分析。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(operation, name, le, type, rejected) (irate(apiserver_admission_controller_admission_duration_seconds_bucket{type=\"admit\"}[$interval])) )",
     "legendFormat": "{{name}} - {{operation}} - {{rejected}}"
    }
   ]
  },
  {
   "title": "准入控制器时延 [validate]",
   "type": "graph",
   "description": "展示使用到的validate类型准入控制器、操作、是否拒绝以及相应的执行时间。\n\n这是内建的准入控制器指标。每个准入控制器都有唯一的名字，可以通过操作、API资源和操作类型维度分析。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(operation, name, le, type, rejected) (irate(apiserver_admission_controller_admission_duration_seconds_bucket{type=\"validate\"}[$interval])) )",
     "legendFormat": "{{name}} - {{operation}} - {{rejected}}"
    }
   ]
  },
  {
   "title": "准入 Webhook 时延 [admit]",
   "type": "graph",
   "description": "展示使用到的admit类型Webhook、操作、是否拒绝以及相应的执行时间。\n\n该指标apiserver_admission_webhook_admission_duration_seconds_bucket类型为histogram，bucket阈值为0.005s, 0.025s, 0.1s, 0.5s, 2.5s.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(operation, name, le, type, rejected) (irate(apiserver_admission_webhook_admission_duration_seconds_bucket{type=\"admit\"}[$interval])) )",
     "legendFormat": "{{name}} - {{operation}} - {{rejected}}"
    }
   ]
  },
  {
   "title": "准入 Webhook 时延 [validating]",
   "type": "graph",
   "description": "该指标类型为histogram，bucket阈值为0.005s, 0.025s, 0.1s, 0.5s, 2.5s.\n准入Webhook默认30s超时。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(operation, name, le, type, rejected) (irate(apiserver_admission_webhook_admission_duration_seconds_bucket{type=\"validating\"}[$interval])) )",
     "legendFormat": "{{name}} - {{operation}} - {{rejected}}"
    }
   ]
  },
  {
   "title": "准入 Webhook 请求QPS",
   "type": "graph",
   "description": "准入 Webhook 请求QPS。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_admission_webhook_admission_duration_seconds_count[$interval]))by(name,operation,type,rejected)",
     "legendFormat": "{{name}} - {{operation}} - {{type}} - {{rejected}}"
    }
   ]
  },
  {
   "title": "客户端分析",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {}
   ]
  },
  {
   "title": "按 Client 维度分析QPS",
   "type": "graph",
   "description": "按 Client 维度分析QPS。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{client!=\"\"}[$interval])) by (client)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "按 Verb + Resource + Client 维度分析QPS [$verb]",
   "type": "graph",
   "description": "按 Verb + Resource + Client 维度分析QPS。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{client!=\"\",verb=~\"$verb\", resource=~\"$resource\"}[$interval]))by(verb,resource,client)",
     "legendFormat": "{{verb}} - {{resource}} - {{client}}"
    }
   ]
  },
  {
   "title": "按 Verb + Resource + Client 维度分析LIST请求QPS（无resourceVersion字段）",
   "type": "graph",
   "description": "按 Verb + Resource + Client 维度分析不带resourceVersion字段的LIST请求",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_no_resourceversion_list_total[$interval]))by(resource,client)",
     "legendFormat": "{{resource}} - {{client}}"
    }
   ]
  }
 ]
}