{
 "title": "APISIX Gateway",
 "description": "MicroService API Gateway Apache APISIX",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "domain",
    "query": {
     "query": "label_values(apisix_http_status,matched_host)"
    }
   },
   {
    "name": "route",
    "label": "route_id",
    "query": {
     "query": "label_values(apisix_http_status{matched_host=~\"$domain\"},route)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "status",
    "label": "状态码",
    "query": {
     "query": "label_values(apisix_http_status{matched_host=~\"$domain\"},code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ApiSix全局视角",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "请求总数/近$interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(apisix_http_requests_total[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "接受的连接/近$interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(apisix_nginx_http_current_connections{state=\"accepted\"}[$interval]))",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "已处理的连接/近$interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(apisix_nginx_http_current_connections{state=\"handled\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "总体QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_requests_total[$interval])) by(job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx连接状态",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections{state=~\"active|reading|writing|waiting\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "域名访问成功 & 失败率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "域名${domain}  访问成功率",
   "type": "timeseries",
   "description": "2xx、3xx、400、401、404、403状态码判定为成功",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{matched_host=~\"${domain}\",code=~\"1.*|2.*|3.*|400|401|404|403\"}[30s])) by(matched_host) / sum(rate(apisix_http_status{matched_host=~\"${domain}\"}[30s])) by(matched_host)",
     "legendFormat": "访问成功率 {{matched_host}}"
    }
   ]
  },
  {
   "title": "域名${domain}  4xx失败率",
   "type": "timeseries",
   "description": "不包含400、401、404、403状态码",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{matched_host=~\"${domain}\",code!~\"1.*|2.*|3.*|400|401|404|403|5.*\"}[30s])) by(matched_host) / sum(rate(apisix_http_status{matched_host=~\"${domain}\"}[30s])) by(matched_host) > 0",
     "legendFormat": "4xx失败率 {{matched_host}}"
    }
   ]
  },
  {
   "title": "域名${domain}  5xx失败率",
   "type": "timeseries",
   "description": "5xx状态码",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{matched_host=~\"${domain}\",code=~\"5.*\"}[30s])) by(matched_host) / sum(rate(apisix_http_status{matched_host=~\"${domain}\"}[30s])) by(matched_host) > 0",
     "legendFormat": " 5xx失败率 {{matched_host}}"
    }
   ]
  },
  { "title": "状态码分布", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "状态码分布(域名：$domain，状态码：$status )",
   "type": "timeseries",
   "description": "域名+状态码粒度请求量",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{ matched_host=~\"${domain}\", route=~\"${route}\", code=~\"${status}\"}[$interval]))by(code) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每个URL的请求数/$interval（RPS）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status{matched_host=~\"$domain\", route=~\"$route\"}[$interval])) by (matched_host,matched_uri) > 0",
     "legendFormat": "{{matched_host}}{{matched_uri}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "总带宽/$interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n  sum(rate(apisix_bandwidth{}[$interval])) by (type)\n)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "每个路由的入口/$interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n  sum(rate(apisix_bandwidth{type=\"ingress\"}[$interval])) by (route)\n)\n",
     "legendFormat": "{{matched_host}}{{matched_uri}}"
    }
   ]
  },
  {
   "title": "每条路由的出口/$interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(rate(apisix_bandwidth{type=\"egress\"}[$interval])) by (route) \n)",
     "legendFormat": "{{matched_host}}{{matched_uri}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Etcd修改索引",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(apisix_etcd_modify_indexes{key=~\"consumers|global_rules|max_modify_index|prev_index|protos|routes|services|ssls|stream_routes|upstreams|x_etcd_index\"}) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Etcd 可达的",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(apisix_etcd_reachable)" }
   ]
  },
  {
   "title": "Nginx metric errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(apisix_nginx_metric_errors_total)"
    }
   ]
  },
  {
   "title": "Nginx共享dict可用空间百分比",
   "type": "timeseries",
   "description": "The free space percent of each nginx shared DICT since APISIX start",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(apisix_shared_dict_free_space_bytes * 100) / apisix_shared_dict_capacity_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}