{
 "title": "Ceph Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": " 集群状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OSD 总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in\n* on(ceph_daemon) group_right(instance, cluster)\nceph_osd_metadata)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSD 活跃数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_in == 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OSD 非活跃数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in != 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSD 在线数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSD 离线数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up != 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "总存储容量",
   "type": "timeseries",
   "description": "表示 Ceph 集群的总存储容量（以字节为单位）。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "存储使用情况",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "使用" },
    {
     "expr": "ceph_cluster_total_bytes - ceph_cluster_total_used_bytes",
     "legendFormat": "剩余"
    }
   ]
  },
  {
   "title": "存储整体使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes / ceph_cluster_total_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "OSD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "写操作延迟【ms】",
   "type": "timeseries",
   "description": "这个指标反映了从客户端发起写请求到数据成功写入 OSD 的时间。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  {
   "title": "数据提交延迟【ms】",
   "type": "timeseries",
   "description": "这个指标反映了从数据被写入 OSD 的日志（Journal）到数据最终被提交到后端存储（如 RADOS 对象存储）的时间。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ceph_osd_commit_latency_ms", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "存储池使用情况",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum((ceph_pool_max_avail) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Available - {{ name }}"
    },
    {
     "expr": "sum((ceph_pool_stored) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Stored - {{ name }}"
    },
    {
     "expr": "sum((ceph_pool_stored_raw) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Raw - {{ name }}"
    }
   ]
  },
  {
   "title": "读写速率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum((irate(ceph_pool_rd_bytes[5m])) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Read - {{ name }}"
    },
    {
     "expr": "sum((irate(ceph_pool_wr_bytes[5m])) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Written - {{ name }}"
    }
   ]
  },
  {
   "title": "Objects in Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((ceph_pool_objects) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Objects - {{ name }}"
    },
    {
     "expr": "sum((ceph_pool_dirty) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Dirty Objects - {{ name }}"
    },
    {
     "expr": "sum((ceph_pool_quota_objects) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Quota Objects - {{ name }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum((irate(ceph_pool_rd[3m])) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Read - {{ name }}"
    },
    {
     "expr": "sum((irate(ceph_pool_wr[3m])) *on (pool_id) group_left(name)(ceph_pool_metadata{})) by (name)",
     "legendFormat": "Write - {{ name }}"
    }
   ]
  },
  {
   "title": "Pool 中 PG 的总数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceph_pg_total * on (pool_id) group_right() ceph_pool_metadata",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool 中 PG 的活跃数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ceph_pg_active * on (pool_id) group_right() ceph_pool_metadata",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}