{
 "title": "KubeControllerManager",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "quantile", "query": "0.99,0.9,0.5" },
   { "name": "interval", "query": "1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Workqueue ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workqueue入队速率",
   "type": "timeseries",
   "description": "Workqueue入队速率。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"ack-cloud-controller-manager\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue深度",
   "type": "timeseries",
   "description": "Workqueue depth: It’s the number of actions waiting in the queue to be performed. It should remain in low values.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"ack-cloud-controller-manager\"}[$interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue处理时延",
   "type": "timeseries",
   "description": "Workqueue latency: It’s the time that kube-controller-manager is taking to fulfill the different actions to keep the desired status of the cluster.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"ack-cloud-controller-manager\"}[5m])) by (name, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU使用量",
   "type": "timeseries",
   "description": "CPU使用量，单位毫核。1核=1000毫核。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpu_utilization_core{container=\"cloud-controller-manager\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "description": "内存使用量，单位字节。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_utilization_byte{container=\"cloud-controller-manager\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kube API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kube API 请求QPS【2xx】",
   "type": "timeseries",
   "description": "对kube-apiserver发起的HTTP请求，从方法（method)、返回值（code) 维度分析。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ack-cloud-controller-manager\",code=~\"2..\"}[$interval])) by (method,code)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Kube API 请求QPS【非2xx】",
   "type": "timeseries",
   "description": "对kube-apiserver发起的HTTP请求，从方法（method)、返回值（code) 维度分析。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ack-cloud-controller-manager\",code!~\"2..\"}[$interval])) by (method,code)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Kube API 请求时延",
   "type": "timeseries",
   "description": "对kube-apiserver发起的HTTP请求时延，从方法（verb)、请求url维度分析。",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(rest_client_request_duration_seconds_bucket{job=\"ack-cloud--kube-controller-manager\"}[$interval])) by (verb,url,le))\n",
     "legendFormat": "{{verb}} - {{url}}"
    }
   ]
  }
 ]
}