{
 "title": "CoreDNS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "DNS 请求量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_requests_total{job=\"kubernetes-coredns\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "DNS 错误率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(increase(coredns_dns_responses_total{job=\"kubernetes-coredns\",rcode=~\"SERVFAIL|REFUSED\"}[$__rate_interval]))/sum(increase(coredns_dns_requests_total{job=\"kubernetes-coredns\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 转发量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(coredns_forward_requests_total{job=\"kubernetes-coredns\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 缓存命中率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(increase(coredns_cache_hits_total{job=\"kubernetes-coredns\"}[$__rate_interval]))/sum(increase(coredns_dns_requests_total{job=\"kubernetes-coredns\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 请求（按协议）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{job=\"kubernetes-coredns\"}[5m])) by (proto) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 请求（按类型）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{job=\"kubernetes-coredns\"}[5m])) by (type) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 转发",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{job=\"kubernetes-coredns\"}[5m])) or vector(0)",
     "legendFormat": "Forward"
    }
   ]
  },
  {
   "title": "DNS 错误率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 * sum(rate(coredns_dns_responses_total{job=\"kubernetes-coredns\",rcode=~\"SERVFAIL|REFUSED\"}[5m]))/sum(rate(coredns_dns_requests_total{job=\"kubernetes-coredns\"}[5m])) or vector(0)",
     "legendFormat": "Failed rate"
    }
   ]
  },
  {
   "title": "缓存命中/未命中",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{job=\"kubernetes-coredns\"}[5m])) or vector(0)",
     "legendFormat": "缓存命中"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{job=\"kubernetes-coredns\"}[5m])) or vector(0)",
     "legendFormat": "未命中"
    }
   ]
  },
  {
   "title": "响应延时（P90）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.9, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"kubernetes-coredns\"}[5m]))by (le)) or vector(0)",
     "legendFormat": "请求响应延时（P90）"
    },
    {
     "expr": "1000*histogram_quantile(0.9, sum(rate(coredns_forward_request_duration_seconds_bucket{job=\"kubernetes-coredns\"}[5m]))by (le)) or vector(0)",
     "legendFormat": "转发请求响应延时（P90）"
    }
   ]
  }
 ]
}