{
 "title": "AWS-Test-Kubernetes-Daemonset",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_daemonset_created, namespace)"
    }
   },
   {
    "name": "daemonset",
    "label": "daemonset",
    "query": {
     "query": "label_values(kube_daemonset_created{namespace=~\"$namespace\"},daemonset)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{namespace=\"${namespace}\"}) by(namespace)"
    },
    {
     "expr": "count(kube_pod_container_info{namespace=\"${namespace}\"}) by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{namespace=\"${namespace}\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{namespace=\"${namespace}\"}) by(namespace)",
     "legendFormat": "secret"
    },
    {
     "expr": "count(kube_deployment_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_job_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_cronjob_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\",namespace=\"${namespace}\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\",namespace=\"${namespace}\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\",namespace=\"${namespace}\"}==1) by(namespace)"
    },
    {
     "expr": "count(kube_deployment_status_replicas_ready{namespace=\"${namespace}\"}<kube_deployment_spec_replicas{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_status_replicas_ready{namespace=\"${namespace}\"}<kube_statefulset_replicas{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{namespace=\"${namespace}\"}>0)by(namespace)"
    },
    {
     "expr": "count(kube_job_status_failed{namespace=\"${namespace}\"} == 1) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"${namespace}\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Pod内存使用率Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, avg(container_memory_working_set_bytes{namespace=\"${namespace}\",pod!=\"\",container!=\"\"}/(container_spec_memory_limit_bytes!=0) * 100) by (container, pod, namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU使用率Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\",container!=\"POD\",pod!=\"\"}[1m]) * 100) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod文件打开数Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "topk(10, sum(container_sockets{namespace=\"${namespace}\",container!=\"\",pod!=\"\"}) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(kube_namespace_labels{namespace=\"kube-system\"}) by(namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_daemonset_created{namespace=\"$namespace\",daemonset=\"$daemonset\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_current_number_scheduled{daemonset=\"$daemonset\",namespace=\"$namespace\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "kube_daemonset_status_number_ready{daemonset=\"$daemonset\",namespace=\"$namespace\"}",
     "legendFormat": "Ready"
    },
    {
     "expr": "kube_daemonset_status_number_ready{daemonset=\"$daemonset\",namespace=\"$namespace\"}/kube_daemonset_status_current_number_scheduled{daemonset=\"$daemonset\",namespace=\"$namespace\"} * 100",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (daemonset)\n* on(daemonset) group_right() max(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (daemonset))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (daemonset)\n* on(daemonset) group_right() max(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (daemonset))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (daemonset)\n* on(daemonset) group_right() max(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"}) by (daemonset))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (daemonset)\n* on(daemonset) group_right() max(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (daemonset))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_info{created_by_kind=\"DaemonSet\",namespace=\"$namespace\",created_by_name=\"$daemonset\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} * (kube_pod_status_phase{namespace=\"$namespace\"} > 0)) by (uid, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"} * (kube_pod_status_ready{namespace=\"$namespace\"} > 0)) by (uid, condition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{namespace=\"$namespace\"}) by (uid)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (uid, container)) by (uid)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container)",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\", created_by_name=\"$daemonset\"}) by (pod)\n* on(pod) group_right() max(container_memory_usage_bytes{container!=\"POD\",container!=\"\",namespace=\"$namespace\"}) by(container, pod)",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "Out: {{pod}}"
    },
    {
     "expr": "-sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod,container)",
     "legendFormat": "In: {{pod}}"
    }
   ]
  },
  {
   "title": "fs writes/reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{ namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (pod)\n* on(pod) group_right() max(rate(container_fs_reads_bytes_total{ namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "Read: {{pod}}/{{container}}"
    },
    {
     "expr": "group(kube_pod_info{ namespace=\"$namespace\",created_by_kind=\"DaemonSet\",pod_ip!=\"\", created_by_name=\"$daemonset\"}) by (pod)\n* on(pod) group_right() max(rate(container_fs_writes_bytes_total{ namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "Write: {{pod}}/{{container}}"
    }
   ]
  }
 ]
}