{
 "title": "AliCloud-Prod-KubernetesDeployment",
 "description": "Kubernetes Deployment Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_created{},namespace)"
    }
   },
   {
    "name": "name",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_created{ namespace=\"$namespace\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{namespace=\"${namespace}\"}) by(namespace)"
    },
    {
     "expr": "count(kube_pod_container_info{namespace=\"${namespace}\"}) by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{namespace=\"${namespace}\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{namespace=\"${namespace}\"}) by(namespace)",
     "legendFormat": "secret"
    },
    {
     "expr": "count(kube_deployment_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_job_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_cronjob_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\",namespace=\"${namespace}\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\",namespace=\"${namespace}\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\",namespace=\"${namespace}\"}==1) by(namespace)"
    },
    {
     "expr": "count(kube_deployment_status_replicas_ready{namespace=\"${namespace}\"}<kube_deployment_spec_replicas{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_status_replicas_ready{namespace=\"${namespace}\"}<kube_statefulset_replicas{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{namespace=\"${namespace}\"}>0)by(namespace)"
    },
    {
     "expr": "count(kube_job_status_failed{namespace=\"${namespace}\"} == 1) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"${namespace}\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Pod内存使用率Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, avg(container_memory_working_set_bytes{namespace=\"${namespace}\",pod!=\"\",container!=\"\"}/(container_spec_memory_limit_bytes!=0) * 100) by (container, pod, namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU使用率Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\",container!=\"POD\",pod!=\"\"}[1m]) * 100) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod文件打开数Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "topk(10, sum(container_sockets{namespace=\"${namespace}\",container!=\"\",pod!=\"\"}) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_labels{namespace=\"$namespace\"})by(namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Time since deployment created.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_deployment_created{namespace=\"$namespace\",deployment=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas(Pods)",
   "type": "stat",
   "description": "工作副本数量统计",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"$name\",namespace=\"$namespace\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"$name\",namespace=\"$namespace\"}",
     "legendFormat": "Ready"
    },
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"$name\",namespace=\"$namespace\"} / kube_deployment_spec_replicas{deployment=\"$name\",namespace=\"$namespace\"}",
     "legendFormat": "Ready Percent"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", created_by_kind=\"ReplicaSet\", pod_ip!=\"\", namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$name\", resource=\"memory\", namespace=\"$namespace\"}"
    },
    {
     "expr": "max(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", created_by_kind=\"ReplicaSet\", pod_ip!=\"\", namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$name\", resource=\"cpu\", namespace=\"$namespace\"}"
    },
    {
     "expr": "max(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", created_by_kind=\"ReplicaSet\", pod_ip!=\"\", namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$name\", namespace=\"$namespace\", container=\"$name\"}"
    },
    {
     "expr": "max(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"$name\",resource=\"memory\"}) by (pod)) "
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", created_by_kind=\"ReplicaSet\", pod_ip!=\"\", namespace=\"$namespace\", owner_kind=\"Deployment\", owner_name=\"$name\", resource=\"cpu\", namespace=\"$namespace\", container=\"$name\"}"
    },
    {
     "expr": "max(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\",container=\"$name\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} * (kube_pod_status_phase{namespace=\"$namespace\"} > 0)) by (uid, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"} * (kube_pod_status_ready{namespace=\"$namespace\"} > 0)) by (uid, condition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{namespace=\"$namespace\"}) by (uid)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (uid, container)) by (uid)"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container)",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    },
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"}) by (pod, container)",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"}) by (pod, container)",
     "legendFormat": "Request: {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage(%)",
   "type": "timeseries",
   "description": "分别将 CPU 使用量除以 CPU 请求量和 CPU 限制量，为每个容器得出 2 条时间线。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container)\n/\nmax(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"}) by (pod, container))",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})\n",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    },
    {
     "expr": "max(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"}))by(container)",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "max(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"}))by(container)",
     "legendFormat": "Request: {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max by(container, pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"})\n/ \nmax(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() (kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"})) by(container, pod)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() sum(container_sockets{namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "stat",
   "description": "The number of network errors including receiving and transmitting.",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() (sum(container_network_receive_errors_total{namespace=\"$namespace\"}) by (pod) + sum(container_network_transmit_errors_total{namespace=\"$namespace\"}) by (pod)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)\n\n",
     "legendFormat": "Receive-Out"
    },
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "Transmit-In"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "Read: {{pod}}/{{container}}"
    },
    {
     "expr": "label_replace(\n  sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"ReplicaSet\", pod_ip!=\"\"}) by (created_by_name, uid, pod, pod_ip, node),\n  \"replicaset\",\n  \"$1\",\n  \"created_by_name\",\n  \"(.+)\"\n) * on(replicaset) group_left() sum(kube_replicaset_owner{namespace=\"$namespace\",owner_kind=\"Deployment\",owner_name=\"$name\"}) by (replicaset)\n* on(pod) group_right() max(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "Write: {{pod}}/{{container}}"
    }
   ]
  }
 ]
}