{
 "title": "Etcd",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "集群信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "集群节点数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(etcd_server_has_leader{job=\"kubernetes-etcd\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader 数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_server_is_leader{job=\"kubernetes-etcd\"} == 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leader 节点",
   "type": "table",
   "description": "etcd集群存活状态。正常情况下有且有一个leader节点。",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_server_is_leader{job=\"kubernetes-etcd\"}==1",
     "legendFormat": "{{ pod }} is leader"
    }
   ]
  },
  {
   "title": "过去一天切主次数",
   "type": "timeseries",
   "description": "最近一天Leader变动次数\n标记切主（网络，OOM，升级等会导致切主）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " changes(etcd_server_leader_changes_seen_total{job=\"kubernetes-etcd\"}[1d])",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  { "title": "资源信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU使用量",
   "type": "timeseries",
   "description": "CPU使用量，单位毫核。\n1核=1000毫核。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu_utilization_core{container=\"etcd\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "description": "内存使用量，单位字节。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_utilization_byte{container=\"etcd\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘大小",
   "type": "timeseries",
   "description": "Etcd数据存储量（单位：字节）\nin use DB size表示真实的数据存储量。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"kubernetes-etcd\"}",
     "legendFormat": "{{ instance }} DB Size"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{job=\"kubernetes-etcd\"}",
     "legendFormat": "{{ instance }} in use DB size"
    }
   ]
  },
  { "title": "集群情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "backend commit 延迟",
   "type": "timeseries",
   "description": "etcd server磁盘延迟",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"kubernetes-etcd\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "kv总数",
   "type": "timeseries",
   "description": "etcd存储数据量（单位：个数）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{job=\"kubernetes-etcd\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "raft proposals 情况",
   "type": "timeseries",
   "description": "raft proposals\ncommit-apply大于0、pending total大于0表示etcd server压力大。\nfailed rate不等于0表示有raft提交失败。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "etcd_server_proposals_committed_total{job=\"kubernetes-etcd\"} - etcd_server_proposals_applied_total{job=\"kubernetes-etcd\"}",
     "legendFormat": "{{ instance }} commit-apply"
    },
    {
     "expr": "rate(etcd_server_proposals_failed_total{job=\"kubernetes-etcd\"}[1m])",
     "legendFormat": "{{ instance }} proposals failed rate"
    },
    {
     "expr": "etcd_server_proposals_pending{job=\"kubernetes-etcd\"}",
     "legendFormat": "{{instance}} proposals pending total"
    }
   ]
  }
 ]
}