{
 "title": "GPU 监控",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "env", "label": "env", "query": "a1-test,a1-prod" },
   {
    "name": "label",
    "label": "label",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL{namespace=\"$env\"},container)"
    }
   },
   {
    "name": "node_ip",
    "query": {
     "query": "label_values(DCGM_FI_DEV_DEC_UTIL{namespace=\"$env\", container=\"$label\"},Hostname)"
    }
   },
   { "name": "gpu", "query": "label_values(gpu)" }
  ]
 },
 "panels": [
  {
   "title": "基础资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node_ip\"}[1m])) by (instance,cluster_vke_volcengine_com_node_name) * 100) ",
       "legendFormat": "{{cluster_vke_volcengine_com_node_name}} ({{instance}})"
      }
     ]
    },
    {
     "title": "内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (sum(node_memory_MemAvailable_bytes{instance=~\"$node_ip\"}) by (instance,cluster_vke_volcengine_com_node_name) / sum(node_memory_MemTotal_bytes{instance=~\"$node_ip\"}) by (instance,cluster_vke_volcengine_com_node_name) * 100 )",
       "legendFormat": "{{cluster_vke_volcengine_com_node_name}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Disk 使用率",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",instance=~\"$node_ip\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",instance=~\"$node_ip\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\",instance=~\"$node_ip\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",instance=~\"$node_ip\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",instance=~\"$node_ip\"})))by(instance,mountpoint,ecs_cname,cluster_vke_volcengine_com_node_name)",
       "legendFormat": "{{cluster_vke_volcengine_com_node_name}} ({{instance}} - 挂载点：{{mountpoint}})"
      }
     ]
    },
    {
     "title": "IO读写请求数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "avg(rate(node_disk_reads_completed_total{instance=~\"${node_ip}\"}[1m])) by (instance,ecs_cname,cluster_vke_volcengine_com_node_name)",
       "legendFormat": "Read: {{cluster_vke_volcengine_com_node_name}} ({{instance}})"
      },
      {
       "expr": "avg(rate(node_disk_writes_completed_total{instance=~\"${node_ip}\"}[1m])) by (instance,ecs_cname,cluster_vke_volcengine_com_node_name)",
       "legendFormat": "Write: {{cluster_vke_volcengine_com_node_name}} ({{instance}})"
      }
     ]
    }
   ]
  },
  { "title": "GPU资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "GPU卡使用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${node_ip}\", gpu=~\"${gpu}\", container=~\"${label}\"}",
     "legendFormat": "{{Hostname}} - {{gpu}} - {{container}}"
    }
   ]
  },
  {
   "title": "节点GPU卡总和使用率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${node_ip}\", container=~\"${label}\"}) by (Hostname)",
     "legendFormat": "{{Hostname}}"
    }
   ]
  },
  {
   "title": "GPU卡显存使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=~\"${node_ip}\", gpu=~\"${gpu}\", container=~\"${label}\"}",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU卡显存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((DCGM_FI_DEV_FB_USED{Hostname=~\"${node_ip}\", container=~\"${label}\"} / (DCGM_FI_DEV_FB_FREE{Hostname=~\"${node_ip}\", container=~\"${label}\"} + DCGM_FI_DEV_FB_USED{Hostname=~\"${node_ip}\", container=~\"${label}\"})) * 100) by (Hostname,gpu)",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "节点GPU卡总和显存使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{Hostname=~\"${node_ip}\", container=~\"${label}\"}) by (Hostname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点GPU卡总和显存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(DCGM_FI_DEV_FB_USED{Hostname=~\"${node_ip}\", container=~\"${label}\"} / (DCGM_FI_DEV_FB_FREE{Hostname=~\"${node_ip}\", container=~\"${label}\"} + DCGM_FI_DEV_FB_USED{Hostname=~\"${node_ip}\", container=~\"${label}\"})) * 100",
     "legendFormat": "{{Hostname}}"
    }
   ]
  },
  {
   "title": "平均温度",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${node_ip}\", gpu=~\"${gpu}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总功率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"${node_ip}\", gpu=~\"${gpu}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU XID 错误",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_XID_ERRORS{instance=~\"${node_ip}\"}",
     "legendFormat": "{{instance}} - {{gpu}}号卡"
    }
   ]
  },
  {
   "title": "使用功率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=~\"${node_ip}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{Hostname}}"
    }
   ]
  },
  {
   "title": "GPU温度",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${node_ip}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU字段标识符",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{Hostname=~\"${node_ip}\", gpu=~\"${gpu}\"} * 1000000",
     "legendFormat": "{{Hostname}} - {{gpu}}"
    }
   ]
  }
 ]
}