{
 "title": "Jvm",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)Filter by datasource/namespace/node.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "serviceName",
    "label": "serviceName",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage_bytes,service_name)"
    }
   },
   {
    "name": "hostName",
    "label": "hostName",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage_bytes{service_name=\"$serviceName\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{service_name=\"$serviceName\", host_name=\"$hostName\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{service_name=\"$serviceName\", host_name=\"$hostName\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service_name=\"$serviceName\", host_name=\"$hostName\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{service_name=\"$serviceName\", host_name=\"$hostName\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{service_name=\"$serviceName\", host_name=\"$hostName\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{service_name=\"$serviceName\", host_name=\"$hostName\", area=\"heap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service_name=\"$serviceName\", host_name=~\"$hostName\"}[5m])) by (host_name)",
       "legendFormat": "{{host_name}} HTTP"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service_name=\"$serviceName\", host_name=~\"$hostName\", status=~\"5..\"}[5m])) by (host_name)",
       "legendFormat": "{{host_name}} HTTP - 5xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{service_name=\"$serviceName\", host_name=~\"$hostName\", status!~\"5..\"}[1m])) by (host_name )/sum(rate(http_server_requests_seconds_count{service_name=\"$serviceName\", host_name=~\"$hostName\", status!~\"5..\"}[1m]))by (host_name )",
       "legendFormat": "{{host_name}} HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{service_name=\"$serviceName\", host_name=~\"$hostName\", status!~\"5..\"})",
       "legendFormat": "{{host_name}} HTTP - MAX"
      }
     ]
    },
    {
     "title": "Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_threads_busy_threads{service_name=\"$serviceName\", host_name=~\"$hostName\",}",
       "legendFormat": "TOMCAT - BSY"
      },
      {
       "expr": "tomcat_threads_current_threads{service_name=\"$serviceName\", host_name=~\"$hostName\",}",
       "legendFormat": "TOMCAT - CUR"
      },
      {
       "expr": "tomcat_threads_config_max_threads{service_name=\"$serviceName\", host_name=\"$hostName\",}",
       "legendFormat": "TOMCAT - MAX"
      },
      {
       "expr": "jetty_threads_busy{service_name=\"$serviceName\", host_name=\"$hostName\",}",
       "legendFormat": "JETTY - BSY"
      },
      {
       "expr": "jetty_threads_current{service_name=\"$serviceName\", host_name=~\"$hostName\",}",
       "legendFormat": "JETTY - CUR"
      },
      {
       "expr": "jetty_threads_config_max{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\"}",
       "legendFormat": "JETTY - MAX"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(host_name) (process_runtime_jvm_memory_usage_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", type=\"heap\"})",
     "legendFormat": "{{host_name}} used:"
    },
    {
     "expr": "sum by(host_name) (process_runtime_jvm_memory_committed_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", type=\"heap\"})",
     "legendFormat": "{{host_name}} committed:"
    },
    {
     "expr": "sum by(host_name) (process_runtime_jvm_memory_limit_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", type=\"heap\"})",
     "legendFormat": "{{host_name}} max:"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(host_name) (process_runtime_jvm_memory_usage_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", type=\"non_heap\"})",
     "legendFormat": "{{host_name}} used:"
    },
    {
     "expr": "sum by(host_name) (process_runtime_jvm_memory_committed_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", type=\"non_heap\"})",
     "legendFormat": "{{host_name}}  committed:"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_limit_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", type=\"non_heap\"}) by (host_name)",
     "legendFormat": "{{host_name}} max:"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_memory_usage_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",}) by (host_name)",
     "legendFormat": "{{host_name}} used:"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_committed_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\"}) by (host_name)",
     "legendFormat": "{{host_name}} committed:"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_limit_bytes{service_name=\"$serviceName\",host_name=~\"$hostName\"}) by (host_name)",
     "legendFormat": "{{host_name}} max:"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_rss_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_swap_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_rss_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\"} + process_memory_swap_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"$serviceName\", host_name=~\"$hostName\"}",
     "legendFormat": "{{host_name}} system:"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{service_name=\"$serviceName\", host_name=~\"$hostName\"}[1h])",
     "legendFormat": "{{host_name}} process-1h:"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_load_1m{service_name=\"$serviceName\", host_name=~\"$hostName\"}",
     "legendFormat": "{{host_name}} system-1m:"
    },
    {
     "expr": "system_cpu_count{service_name=\"$serviceName\", host_name=~\"$hostName\"}",
     "legendFormat": "{{host_name}} cpus:"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_threads_count{service_name=\"$serviceName\", host_name=~\"$hostName\",daemon=\"false\"}",
     "legendFormat": "live"
    },
    {
     "expr": "process_runtime_jvm_threads_count{service_name=\"$serviceName\", host_name=~\"$hostName\",daemon=\"true\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{namespace=~\"$namespace\",app=~\"$application\", kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{service_name=\"$serviceName\", host_name=~\"$hostName\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{service_name=\"$serviceName\", host_name=\"$hostName\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{service_name=\"$serviceName\", host_name=~\"$hostName\"}[5m])",
     "legendFormat": "{{host_name}} {{level}}:"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{service_name=\"$serviceName\", host_name=~\"$hostName\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{service_name=\"$serviceName\", host_name=~\"$hostName\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_usage_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",type=\"heap\"}",
     "legendFormat": "{{host_name}} used {{id}}:"
    },
    {
     "expr": "process_runtime_jvm_memory_committed_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",type=\"heap\"}",
     "legendFormat": "{{host_name}} commited {{id}}"
    },
    {
     "expr": "process_runtime_jvm_memory_limit_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",type=\"heap\"}",
     "legendFormat": "{{host_name}} max {{id}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_usage_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",type=\"non_heap\"}",
     "legendFormat": "{{host_name}} used {{id}}"
    },
    {
     "expr": "process_runtime_jvm_memory_committed_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",type=\"non_heap\"}",
     "legendFormat": "{{host_name}} commited {{id}}"
    },
    {
     "expr": "process_runtime_jvm_memory_limit_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",type=\"non_heap\"}",
     "legendFormat": "{{host_name}} max {{id}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(process_runtime_jvm_gc_duration_seconds_count{service_name=\"$serviceName\", host_name=~\"$hostName\"}[5m])",
     "legendFormat": "{{host_name}} {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_runtime_jvm_gc_duration_seconds_sum{service_name=\"$serviceName\", host_name=~\"$hostName\"}[1m])/rate(process_runtime_jvm_gc_duration_seconds_count{service_name=\"$serviceName\", host_name=~\"$hostName\"}[1m])",
     "legendFormat": "{{host_name}}  avg {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{service_name=\"$serviceName\", host_name=~\"$hostName\"}[1m])",
     "legendFormat": "{{host_name}} allocated"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_classes_current_loaded{service_name=\"$serviceName\", host_name=~\"$hostName\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(process_runtime_jvm_classes_current_loaded{service_name=\"$serviceName\", host_name=~\"$hostName\"}[5m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_buffer_usage_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", pool=\"direct\"}",
     "legendFormat": "{{host_name}} used"
    },
    {
     "expr": "process_runtime_jvm_buffer_limit_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", pool=\"direct\"}",
     "legendFormat": "{{host_name}} capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_buffer_count{service_name=\"$serviceName\", host_name=~\"$hostName\", pool=\"direct\"}",
     "legendFormat": "{{host_name}}  count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_buffer_usage_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\", pool=\"mapped\"}",
     "legendFormat": "{{host_name}}  used"
    },
    {
     "expr": "process_runtime_jvm_buffer_limit_bytes{service_name=\"$serviceName\", host_name=~\"$hostName\",pool=\"mapped\"}",
     "legendFormat": "{{host_name}} capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_buffer_count{service_name=\"$serviceName\", host_name=~\"$hostName\", pool=\"mapped\"}",
     "legendFormat": "{{host_name}}  count"
    }
   ]
  }
 ]
}