{
 "title": "集群监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "节点信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{kernel_version!=\"\",node!~\"vci.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NotReady节点数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{kernel_version!=\"\",node!~\"vci.*\"})-count(kube_node_status_condition{condition=\"Ready\", status=\"true\",node!~\"vci.*\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PIDPressure节点数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{status=\"true\",condition=\"PIDPressure\"}==1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DiskPressure节点数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{status=\"true\",condition=\"DiskPressure\"}==1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemoryPressure节点数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{status=\"true\",condition=\"MemoryPressure\"}==1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NetworkUnavailable节点数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{status=\"true\",condition=\"NetworkUnavailable\"}==1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "集群资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "集群节点内存使用",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\",node!~\"vci.*\"})",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{}-node_memory_MemAvailable_bytes{})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "集群节点 CPU 使用",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode=\"user\"}[5m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",node!~\"vci.*\"}) ",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "集群资源数据量",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sort_desc(sum(etcd_object_counts) by(resource,endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kubelet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Kubelet与容器运行时交互总次数【1m】",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "irate(sum(kubelet_runtime_operations_total{}[1m]) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubelet与容器运行时交互失败次数【1m】",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 27 },
   "targets": [
    {
     "expr": "irate(sum(kubelet_runtime_operations_errors_total{}[1m]) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "集群操作容器总错误率【1m】",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(sum(kubelet_runtime_operations_errors_total{}[1m]) by (instance)) / irate(sum(kubelet_runtime_operations_total{}[1m]) by (instance)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Kubelet客户端证书的剩余有效时间",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(sum(kubelet_certificate_manager_client_ttl_seconds{}) by (instance) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubelet GET 请求QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(sum(kubelet_http_requests_total{method=\"GET\"}) by (instance)[1m]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kubelet POST 请求QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(sum(kubelet_http_requests_total{method=\"POST\"}) by (instance)[1m]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}