{
 "title": "AliCloud-Test-MongoDB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(mongodb_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{instance=\"${instance}\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_health{instance=\"${instance}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "mongodb_memory{instance=\"${instance}\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "irate(mongodb_connections{instance=\"${instance}\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "工作负载",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(mongodb_op_counters_total{instance=\"${instance}\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "网络流量IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(mongodb_network_bytes_total{instance=\"${instance}\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "TTL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"${instance}\"}[5m])",
     "legendFormat": "ttl_deleted_documents"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_passes_total{instance=\"${instance}\"}[5m])",
     "legendFormat": "ttl_passes"
    }
   ]
  }
 ]
}