{
 "title": "AliCloud-Test-MySQL",
 "description": "MySQL指标监控",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "label": "Server",
    "query": {
     "query": "label_values(mysql_exporter_collector_duration_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(mysql_global_status_uptime)/86400",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "MySQL监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "连接数/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(mysql_global_status_connections{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "连接数"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mysql_global_status_threads_connected{instance=~\"^$Server$\"})",
     "legendFormat": "threads_connected：当前打开连接数"
    },
    {
     "expr": "avg(mysql_global_status_threads_running{instance=~\"^$Server$\"})",
     "legendFormat": "threads_running：当前活跃线程数"
    }
   ]
  },
  {
   "title": "磁盘IO/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_reads[5m]) * 16384\n",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(mysql_global_status_innodb_data_writes[5m]) * 16384",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "流量吞吐(KB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_bytes_sent{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "bytes_sent"
    },
    {
     "expr": "avg(irate(mysql_global_status_bytes_received{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "bytes_received"
    }
   ]
  },
  {
   "title": "查询QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_queries{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "慢查询QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_slow_queries{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "slow_queries"
    }
   ]
  },
  {
   "title": "刷盘次数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_fsyncs[5m])",
     "legendFormat": "mysql.innodb_data_fsyncs"
    }
   ]
  },
  {
   "title": "Table锁",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_table_locks_immediate{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "table_locks_immediate"
    },
    {
     "expr": "avg(irate(mysql_global_status_table_locks_waited{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "table_locks_waited"
    }
   ]
  },
  {
   "title": "临时对象",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_created_tmp_tables{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "tmp_tables"
    },
    {
     "expr": "avg(irate(mysql_global_status_created_tmp_disk_tables{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "tmp_disk_tables"
    },
    {
     "expr": "avg(irate(mysql_global_status_created_tmp_files{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "tmp_files"
    }
   ]
  },
  {
   "title": "InnoDB 监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InnoDB缓冲池使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(mysql_global_status_innodb_buffer_pool_bytes_data / mysql_global_variables_innodb_buffer_pool_size) * 100",
     "legendFormat": "innodb_buffer"
    }
   ]
  },
  {
   "title": "InnoDB CRUD行数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_innodb_system_rows_read{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "avg(irate(mysql_global_status_innodb_system_rows_inserted{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "insert"
    },
    {
     "expr": "avg(irate(mysql_global_status_innodb_system_rows_updated{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "update"
    },
    {
     "expr": "avg(irate(mysql_global_status_innodb_system_rows_deleted{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool请求QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(irate(mysql_global_status_innodb_buffer_pool_write_requests{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "InnoDB Data 读写吞吐",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_innodb_data_written{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "avg(irate(mysql_global_status_innodb_data_read{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "InnoDB Redo 写QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mysql_global_status_innodb_log_writes{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "log_writes"
    },
    {
     "expr": "avg(irate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "log_fsyncs"
    },
    {
     "expr": "avg(irate(mysql_global_status_innodb_log_write_requests{instance=~\"^$Server$\"}[1m]))",
     "legendFormat": "log_write_requests"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool命中率",
   "type": "graph",
   "description": "命中率 = 1 表示所有请求都在缓冲池中命中，无需从磁盘读取。\n命中率接近 0 表示大多数请求都需要从磁盘读取，缓存性能较低。",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(\n  rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"^$Server$\"}[3m])\n  -\n  rate(mysql_global_status_innodb_buffer_pool_reads{instance=~\"^$Server$\"}[3m])\n)\n/\nrate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"^$Server$\"}[3m])\n",
     "legendFormat": "缓存命中率"
    }
   ]
  }
 ]
}