{
 "title": "Prod-Proxy",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(nginx_server_bytes{service_name=\"prod-nginx-exporter\"},service_name)"
    }
   },
   {
    "name": "Host",
    "query": {
     "query": "label_values(nginx_server_bytes{service_name=~\"$Instance\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nginx_server_connections{service_name=~\"$Instance\", status=~\"active|writing|reading|waiting\"}",
     "legendFormat": "{{service_name}} - {{status}}"
    }
   ]
  },
  {
   "title": "缓存",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_server_cache{service_name=~\"$Instance\", host=~\"^$Host$\"}[5m])) by (status,host)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Nginx请求状态",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_server_requests{service_name=~\"$Instance\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Upstream上游请求状态",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_requests{service_name=~\"$Instance\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Nginx请求处理平均时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(nginx_server_requestMsec{service_name=~\"$Instance\", host=~\"^$Host$\"}) by (service_name,host)",
     "legendFormat": "{{service_name}} - {{host}}"
    }
   ]
  },
  {
   "title": "Upstream上游请求处理平均时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(nginx_upstream_requestMsec{service_name=~\"$Instance\"}) by (instance,backend)",
     "legendFormat": "{{service_name}} - {{backend}}"
    }
   ]
  },
  {
   "title": "Nginx网络流量",
   "type": "timeseries",
   "description": "Nginx的网络出入流量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_server_bytes{service_name=~\"$Instance\", host=~\"^$Host$\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream上游网络流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_bytes{service_name=~\"$Instance\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstrean上游响应时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(nginx_upstream_responseMsec{service_name=~\"$Instance\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  }
 ]
}