{
 "title": "AliCloud-Prod-ECS",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(describe_node_process_cpu_info{tags!=\",大数据,\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "概括",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "节点总数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(node_uname_info)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "进程总数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(describe_node_process_cpu_info)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU cores总数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cpu" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode='system'})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "内存总数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "磁盘容量总数",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "节点CPU使用率Top(10)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10,100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",tags!=\",大数据,\"}[5m])) by (instance,service_id,ecs_cname) * 100) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "节点Memory使用率Top(10)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10,100 - (node_memory_MemAvailable_bytes{tags!=\",大数据,\"} / node_memory_MemTotal_bytes{tags!=\",大数据,\"} * 100))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "节点磁盘使用率Top(10)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk(10,max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",tags!=\",大数据,\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",tags!=\",大数据,\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\",tags!=\",大数据,\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",tags!=\",大数据,\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(ecs_cname,instance,service_id))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "进程CPU使用率Top(10)「单实例」",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10,describe_node_process_cpu_info{instance=\"$instance\",name!=\"containerd-shim\", name!=\"containerd-shim-runc-v2\",})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "进程内存使用率Top(10)「单实例」",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "expr": "topk(10,describe_node_process_memory_info{instance=\"${instance}\", name!=\"containerd-shim\", name!=\"containerd-shim-runc-v2\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "进程文件打开数Top(10)「单实例」",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "targets": [
      {
       "expr": "topk(10,describe_node_process_openfiles_info{instance=\"$instance\",name!=\"containerd-shim\", name!=\"containerd-shim-runc-v2\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance,service_id,ecs_cname) * 100) ",
     "legendFormat": "{{ecs_cname}}{{service_id}}（{{instance}}）"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)",
     "legendFormat": "{{ecs_cname}}{{service_id}}（{{instance}}）"
    }
   ]
  },
  {
   "title": "Disk 使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(ecs_cname,instance,service_id)",
     "legendFormat": "{{ecs_cname}}{{service_id}}（{{instance}}）"
    }
   ]
  },
  {
   "title": "Sockets 打开总数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(label_replace(max(node_sockstat_TCP_alloc{tags!=\",大数据,\"}) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "网卡流量In/Out「单实例」",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(label_replace(max(irate(node_network_receive_bytes_total{tags!=\",大数据,\",instance=\"${instance}\"}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "legendFormat": "In: {{instance}}"
    },
    {
     "expr": "sum(label_replace(max(irate(node_network_transmit_bytes_total{tags!=\",大数据,\",instance=\"${instance}\"}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(instance)",
     "legendFormat": "Out: {{instance}}"
    }
   ]
  },
  {
   "title": "IO读写请求数「单实例」",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg(rate(node_disk_reads_completed_total{tags!=\",大数据,\",instance=\"${instance}\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(rate(node_disk_writes_completed_total{tags!=\",大数据,\",instance=\"${instance}\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "丢包率",
   "type": "timeseries",
   "description": "丢包率=成功发包数/总发包数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(fping_lost_count[5m])/avg_over_time(fping_sent_count[5m]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "网络延迟",
   "type": "timeseries",
   "description": "网络延迟=总耗时/成功发包数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fping_rtt_sum / fping_rtt_count * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "进程", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "进程CPU「单实例」",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "describe_node_process_cpu_info{instance=\"$instance\",name!=\"containerd-shim\", name!=\"containerd-shim-runc-v2\"}",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  },
  {
   "title": "进程内存「单实例」",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "describe_node_process_memory_info{instance=\"${instance}\", name!=\"containerd-shim\", name!=\"containerd-shim-runc-v2\"}",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  },
  {
   "title": "进程文件打开数「单实例」",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "describe_node_process_openfiles_info{instance=\"$instance\",name!=\"containerd-shim\", name!=\"containerd-shim-runc-v2\"}",
     "legendFormat": "{{name}} - Pid: {{pid}}"
    }
   ]
  }
 ]
}