{
 "title": "AWS-Prod-RocketMQ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rocketmq_brokeruntime_commitlog_disk_ratio) by (brokerIP) * 100",
     "legendFormat": "{{brokerIP}}"
    }
   ]
  },
  {
   "title": "Broker TPS/QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_broker_tps", "legendFormat": "TPS-{{broker}}" },
    { "expr": "rocketmq_broker_qps", "legendFormat": "QPS-{{broker}}" }
   ]
  },
  {
   "title": "消息积压",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic) and (sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic) > 0)",
     "legendFormat": "Group: {{group}} Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "生产者TPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_tps) by (topic)",
     "legendFormat": "生产者-TPS-{{topic}}"
    }
   ]
  },
  {
   "title": "消费者TPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_tps) by (topic)",
     "legendFormat": "消费者-TPS-{{topic}}"
    }
   ]
  },
  {
   "title": "生产者每秒消息大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_message_size) by (topic)",
     "legendFormat": "生产者-{{topic}}"
    }
   ]
  },
  {
   "title": "消费者每秒消息大小",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_message_size) by (topic)",
     "legendFormat": "消费者-{{topic}}"
    }
   ]
  },
  {
   "title": "生产消息进度-Offset",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset) by (broker,topic)",
     "legendFormat": "生产者-{{topic}}"
    }
   ]
  },
  {
   "title": "消费消息进度-Offset",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_consumer_offset) by (broker,topic)",
     "legendFormat": "消费者-{{topic}}"
    }
   ]
  },
  {
   "title": "消费组的消费延时时间",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rocketmq_group_get_latency_by_storetime) by (broker,group,topic)) and (sum(rocketmq_group_get_latency_by_storetime) by (broker,group,topic) > 0)",
     "legendFormat": "Group: {{group}} - Topic: {{topic}}"
    }
   ]
  }
 ]
}