{
 "title": "Scheduler",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m" },
   { "name": "quantile", "label": "Quantile", "query": "0.5,0.9,0.99" }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "存活的调度器实例",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(scheduler_pod_scheduling_attempts_sum{job=\"ack-scheduler\"})by(instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "调度器尝试抢占总次数",
   "type": "stat",
   "description": "通过驱逐低优先级 Pod 来为高优先级 Pod 腾出资源空间，从而使其能够成功调度到节点上。",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_preemption_attempts_total{job=\"ack-scheduler\"} or vector(0)"
    }
   ]
  },
  {
   "title": "Scheduler Pending Pods",
   "type": "timeseries",
   "description": "Pending Pod的数量。根据队列种类。“active”代表activeQ的Pod数量，“backoff”代表backoffQ的Pod数量，“unschedulable”代表不可调度的Pod数量。",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scheduler_pending_pods{job=\"ack-scheduler\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Scheduler 缓存数据统计",
   "type": "timeseries",
   "description": "调度器缓存中的节点、Pod和 Assumed（bound）Pod的数量。",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scheduler_scheduler_cache_size{job=\"ack-scheduler\",type=\"nodes\"}",
     "legendFormat": "Node Count: {{pod_name}}"
    },
    {
     "expr": "scheduler_scheduler_cache_size{job=\"ack-scheduler\",type=\"pods\"}",
     "legendFormat": "Pods Count:  {{pod_name}}"
    },
    {
     "expr": "scheduler_scheduler_cache_size{job=\"ack-scheduler\",type=\"assumed_pods\"}",
     "legendFormat": "Assumed Pods Count:  {{pod_name}}"
    }
   ]
  },
  {
   "title": "资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "description": "内存使用量，单位字节。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_utilization_byte{container=\"kube-scheduler\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "CPU使用量",
   "type": "timeseries",
   "description": "CPU使用量，单位毫核。1核=1000毫核。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu_utilization_core{container=\"kube-scheduler\"}*1000",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Kube API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kube API 请求QPS【2xx】",
   "type": "timeseries",
   "description": "调度器对kube-apiserver发起的HTTP请求，从方法（method)、返回值（code) 维度分析。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ack-scheduler\",code=~\"2..\"}[$interval])) by (method,code)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Kube API 请求QPS【非2xx】",
   "type": "timeseries",
   "description": "调度器对kube-apiserver发起的HTTP请求，从方法（method)、返回值（code) 维度分析。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ack-scheduler\",code!~\"2..\"}[$interval])) by (method,code)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Kube API 请求时延",
   "type": "graph",
   "description": "调度器对kube-apiserver发起的HTTP请求时延，从方法（verb)、请求url维度分析。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(rest_client_request_duration_seconds_bucket{job=\"ack-scheduler\"}[$interval])) by (verb,url,le))",
     "legendFormat": "{{verb}} - {{url}}"
    }
   ]
  }
 ]
}