{
 "title": "AliCloud-Prod-Kubernetes-Statefulset",
 "description": "Kubernetes StatefulSet Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_statefulset_created{},namespace)"
    }
   },
   {
    "name": "name",
    "label": "StatefulSet",
    "query": {
     "query": "label_values(kube_statefulset_created{namespace=\"$namespace\"}, statefulset)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{namespace=\"${namespace}\"}) by(namespace)"
    },
    {
     "expr": "count(kube_pod_container_info{namespace=\"${namespace}\"}) by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{namespace=\"${namespace}\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{namespace=\"${namespace}\"}) by(namespace)",
     "legendFormat": "secret"
    },
    {
     "expr": "count(kube_deployment_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_job_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_cronjob_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\",namespace=\"${namespace}\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\",namespace=\"${namespace}\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\",namespace=\"${namespace}\"}==1) by(namespace)"
    },
    {
     "expr": "count(kube_deployment_status_replicas_ready{namespace=\"${namespace}\"}<kube_deployment_spec_replicas{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_status_replicas_ready{namespace=\"${namespace}\"}<kube_statefulset_replicas{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{namespace=\"${namespace}\"}>0)by(namespace)"
    },
    {
     "expr": "count(kube_job_status_failed{namespace=\"${namespace}\"} == 1) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_created{namespace=\"${namespace}\"}) by (namespace)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{namespace=\"${namespace}\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Pod内存使用率Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, avg(container_memory_working_set_bytes{namespace=\"${namespace}\",pod!=\"\",container!=\"\"}/(container_spec_memory_limit_bytes!=0) * 100) by (container, pod, namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU使用率Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{namespace=\"${namespace}\",container!=\"\",container!=\"POD\",pod!=\"\"}[1m]) * 100) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod文件打开数Top(10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "topk(10, sum(container_sockets{namespace=\"${namespace}\",container!=\"\",pod!=\"\"}) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_labels{namespace=\"$namespace\"})by(namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Time since StatefulSet created.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_statefulset_created{namespace=\"$namespace\",statefulset=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas(Pods)",
   "type": "stat",
   "description": "Number of desired replicas.",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_ready{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_ready{statefulset=\"$name\",namespace=\"$namespace\"}) / max(kube_statefulset_replicas{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", pod_ip!=\"\", created_by_name=\"$name\", resource=\"memory\", namespace=\"$namespace\"}"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", pod_ip!=\"\", created_by_name=\"$name\", resource=\"cpu\", namespace=\"$namespace\"}"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", pod_ip!=\"\", created_by_name=\"$name\", namespace=\"$namespace\", container!=\"\"}"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", created_by_kind=\"StatefulSet\", pod_ip!=\"\", created_by_name=\"$name\", resource=\"cpu\", namespace=\"$namespace\"}"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",created_by_name=\"$name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} * (kube_pod_status_phase{namespace=\"$namespace\"} > 0)) by (uid, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"} * (kube_pod_status_ready{namespace=\"$namespace\"} > 0)) by (uid, condition)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{namespace=\"$namespace\"}) by (uid)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (uid, container)) by (uid)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "展示该工作负载每个 Pod 的 CPU 使用量。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container,image)",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"}) by (pod, container,image)",
     "legendFormat": "Request: {{pod}}/{{container}}"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"}) by (pod, container,image)",
     "legendFormat": "Limit: {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container)\n/\nmax(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"}) by (pod, container))",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "展示该工作负载的每个 Pod 内存使用量。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(container_memory_usage_bytes{container!=\"POD\",container!=\"\",namespace=\"$namespace\"}) by(container, pod)",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"}) by(container, pod)",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"}) by(container, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(container_memory_usage_bytes{container!=\"POD\",container!=\"\",namespace=\"$namespace\"}) by(container, pod)\n/\nmax(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"}) by(container, pod))",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}\n* on(pod) group_right() container_sockets{namespace=\"$namespace\",container!=\"\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "stat",
   "description": "The number of network errors including receiving and transmitting.",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}\n* on(pod) group_right() container_network_receive_errors_total{namespace=\"$namespace\"} + container_network_transmit_errors_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "Out: {{pod}}"
    },
    {
     "expr": "-sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod,container)",
     "legendFormat": "In: {{pod}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{ namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_fs_reads_bytes_total{ namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "Read: {{pod}}/{{container}}"
    },
    {
     "expr": "group(kube_pod_info{ namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_fs_writes_bytes_total{ namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "Write: {{pod}}/{{container}}"
    }
   ]
  }
 ]
}