{
 "title": "业务接口监控",
 "description": "Infra montor metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(duration_milliseconds_sum{job=~\".*aibuild\"},service_name)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(duration_milliseconds_sum{job=~\"$app\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  { "title": "业务流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "整体流量请求成功率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=~\".*aibuild\",http_status_code=~\"2.*|1.*|3.*\"}) / sum(http_server_duration_milliseconds_count{job=~\".*aibuild\"})"
    }
   ]
  },
  {
   "title": "整体流量请求异常率（4xx ）",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=~\".*aibuild\",http_status_code=~\"4.*\"}) / sum(http_server_duration_milliseconds_count{job=~\".*aibuild\"})"
    }
   ]
  },
  {
   "title": "整体流量请求失败率（5xx）",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=~\".*aibuild\",http_status_code=~\"5.*\"}) / sum(http_server_duration_milliseconds_count{job=~\".*aibuild\"})"
    }
   ]
  },
  {
   "title": "整体接口流量QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(rate(http_server_duration_milliseconds_count{job=~\".*aibuild\", http_route=~\"/.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "接口耗时", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "接口平均响应耗时[5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(duration_milliseconds_sum{span_kind=\"SPAN_KIND_SERVER\", job=~\"$app\", http_route=~\"$route\", http_status_code!=\"\"}[5m]) / duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", job=~\"$app\", http_route=~\"$route\", http_status_code!=\"\"}) by(host_name,http_route, http_method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "接口吞吐量 (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(http_server_duration_milliseconds_count{job=~\"$app\",http_route=~\"$route\"}[5m])) by(http_route))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, http_route) (rate(http_server_duration_milliseconds_bucket{job=~\"$app\", http_route!=\"\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, http_route) (rate(http_server_duration_milliseconds_bucket{job=~\"$app\", http_route!=\"\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P75",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by (le, http_route) (rate(http_server_duration_milliseconds_bucket{job=~\"$app\", http_route!=\"\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, http_route) (rate(http_server_duration_milliseconds_bucket{job=~\"$app\", http_route!=\"\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "接口成功率/失败率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "接口请求成功率(单个接口)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=~\"$app\",http_status_code=~\"2.*|1.*|3.*\",http_route=\"$route\"}) / sum(http_server_duration_milliseconds_count{job=~\"$app\",http_route=\"$route\"}) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "接口请求失败率(单个接口)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=~\"$app\",http_status_code=~\"5.*\",http_route=\"$route\"}) / sum(http_server_duration_milliseconds_count{job=~\"$app\",http_route=\"$route\"}) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "错误接口日志",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "{app=\"apisix\"} |= `` | json | host=\"wegic.ai\" | status=~\"5.*\""
    }
   ]
  }
 ]
}